# Generated by Django 3.2.2 on 2021-07-01 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfrstapp', '0014_proyectos_url_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='datos',
            field=models.IntegerField(default=0),
        ),
    ]
